/** Generic UI chrome strings (mechanic-level, not game-specific; game copy lives in packs). */
export const UI_COPY = {
  /** Working title. One place to rename the app. */
  appName: 'Whose Is It?',
  loading: 'Shuffling the deck',
  guesses: 'guesses in',
  guessedRight: 'guessed right',
  nobody: 'Nobody got it',
  lock: 'Lock in',
  reveal: 'Reveal',
  next: 'Next',
  finish: 'Final scores',
  fullscreen: 'Full screen',
  exitFullscreen: 'Exit full screen',
  join: 'Join',
  roomCode: 'Room code',
  roomCodeHint: '4 letters, shown on the host screen',
  yourName: 'Your name',
  joinError: 'Enter the 4-letter room code and your name.',
  lockGuess: 'Lock in guess',
  of: 'of',
  points: 'pts',
  correctGuesses: 'correct',
  fooled: 'fooled',
  youPlaced: 'You placed',
  youreIn: 'You’re in.',
  lobbyWait: 'Watch the big screen. The host starts the game.',
  yourGuess: 'Your guess',
  gotIt: 'You got it.',
  missed: 'Not this time.',
  noGuess: 'No guess this round.',
  itWas: 'It was',
  winnerIs: 'Winner',
  playAgain: 'Play again',
  standings: 'Standings',
  hostControls: 'Host controls',
  shortcuts: 'Space next · L lock · R reveal · F full screen',
  create: {
    title: 'New game',
    intro: 'Pick a pack, add everyone’s entries, and open the lobby. Nothing leaves this laptop.',
    stepPack: 'Pick a pack',
    stepEntries: 'Add entries',
    stepSettings: 'Settings',
    intakePaste: 'Paste entries',
    intakeLive: 'Players submit in the lobby',
    pasteLabel: 'Entries, one per line',
    pasteHint: 'Name | entry. Commas and tabs work too, so you can paste from a spreadsheet.',
    useSample: 'Use sample entries',
    liveHint: 'Players type their entry on their phone while they wait in the lobby.',
    entriesReady: 'entries ready',
    lineError: 'Line',
    timer: 'Guess timer',
    seconds: 's',
    scoring: 'Scoring',
    scoringModes: {
      competitive: 'Points & places',
      light: 'Awards only',
      none: 'Just for fun',
    },
    hostOnly: 'Host-only mode',
    hostOnlyHint: 'No phones: players shout guesses and you tally on this screen. Always works.',
    open: 'Open lobby',
    back: 'Back to setup',
    joinAt: 'Join at',
    or: 'or scan',
    qrPending: 'QR code arrives in Phase 2',
    joined: 'joined',
    waitingFor: 'Waiting for players…',
    start: 'Start game',
    minimumHint: 'Needs at least 3 entries.',
  },
  demo: {
    title: 'How a game runs',
    intro: 'The host screen and one player’s phone, side by side and in sync. You play one player on the phone; everyone else is simulated.',
    host: 'Shared screen · host laptop on the call',
    phone: 'A player’s phone',
    restart: 'Restart demo',
    steps: [
      { who: 'Host', what: 'Pick a pack, paste entries, open the lobby' },
      { who: 'Players', what: 'Join on their phones with the room code' },
      { who: 'Host', what: 'Start game. Each entry is dealt to the big screen' },
      { who: 'Players', what: 'Read it on their phone too, and guess whose it is' },
      { who: 'Everyone', what: 'Reveal, then the next entry, then final standings' },
    ],
    hint: 'Start on the phone: tap Join. Then on the host: Open lobby, then Start game.',
  },
  parseErrors: {
    missingSeparator: 'needs a | between name and entry',
    missingName: 'is missing a name',
    missingText: 'is missing the entry',
    tooLong: 'is longer than this pack allows',
  },
} as const;
