/** Generic UI chrome strings (mechanic-level, not game-specific; game copy lives in packs). */
export const UI_COPY = {
  /** Working title. One place to rename the app. */
  appName: 'Whose Is It?',
  loading: 'Shuffling the deck',
  guesses: 'guesses in',
  guessedRight: 'guessed right',
  nobody: 'Nobody got it',
  lock: 'Lock in',
  reveal: 'Reveal',
  next: 'Next',
  finish: 'Final scores',
  fullscreen: 'Full screen',
  exitFullscreen: 'Exit full screen',
  join: 'Join',
  roomCode: 'Room code',
  roomCodeHint: '4 letters, shown on the host screen',
  yourName: 'Your name',
  joinError: 'Enter the 4-letter room code and your name.',
  lockGuess: 'Lock in guess',
  of: 'of',
  points: 'pts',
  correctGuesses: 'correct',
  fooled: 'fooled',
  youPlaced: 'You placed',
  winnerIs: 'Winner',
  playAgain: 'Play again',
  standings: 'Standings',
  hostControls: 'Host controls',
  shortcuts: 'Space next · L lock · R reveal · F full screen',
} as const;
