/** Generic UI chrome strings (mechanic-level, not game-specific; game copy lives in src/content/game.json). */
export const UI_COPY = {
  /** The app's name. One place to rename it. */
  appName: 'Tell',
  /** The public source, linked from the console hello. */
  repo: 'https://github.com/bmarshall511/fueled-tell',
  tagline: 'Everyone has a story. Can you tell whose?',
  loading: 'Shuffling the deck',
  guesses: 'guesses in',
  guessedRight: 'guessed right',
  nobody: 'Nobody got it',
  lock: 'Lock in',
  reveal: 'Reveal',
  next: 'Next',
  start: 'Start game',
  finish: 'Final scores',
  fullscreen: 'Full screen',
  exitFullscreen: 'Exit full screen',
  sound: 'Sound',
  soundOn: 'Sound on',
  soundOff: 'Sound off',
  menu: 'Menu',
  close: 'Close',
  of: 'of',
  points: 'pts',
  correctGuesses: 'correct',
  fooled: 'fooled',
  youPlaced: 'You placed',
  winnerIs: 'Winner',
  standings: 'Standings',
  hostControls: 'Host controls',
  shortcuts: 'Space next · L lock · R reveal · M sound · F full screen',
  drumroll: 'Revealing in',

  crash: {
    title: 'Something went wrong',
    body: 'Your game is safe. Reload to pick up where you left off.',
    reload: 'Reload',
  },

  landing: {
    host: 'Host a game',
    hostHint: 'On the device whose screen you’ll share on the call.',
    join: 'Join a game',
    joinHint: 'Got a room code from the shared screen? Enter it here.',
    demo: 'See how it works',
    demoHint: 'The shared screen and a player’s screen, side by side.',
    install: 'Install Tell',
    how: [
      'Everyone sends a short true story (or types it in live when they join).',
      'The host shares their screen. Players join with a 4-letter code.',
      'Each story is dealt to the shared screen. Everyone guesses whose it is on their own device.',
      'Reveal, points, and a podium at the end.',
    ],
  },

  setup: {
    title: 'New game',
    editTitle: 'Edit lobby',
    headingLead: 'Who’s',
    headingGlow: 'playing?',
    lede: 'Add each person and their entry. You can also let people add their own when they join.',
    privacy: 'Private · don’t share your screen yet',
    privacyShort: 'Private',
    choices: {
      paste: { title: 'Paste a list', body: 'From Slack, a doc or a spreadsheet. You’ll see every row before anything’s added.' },
      one: { title: 'Add one by one', body: 'Type a name and their entry. Press Enter to add the next.' },
      live: { title: 'Players add their own', body: 'Everyone types theirs when they join the lobby.' },
    },
    sampleLead: 'Just exploring?',
    sampleLink: 'Try it with sample entries',
    liveToggle: 'Players add their own',
    liveInfo: 'Players type their entry when they join. Anyone you add here is already in.',
    preview: 'Preview of the shared screen',
    previewEmpty: 'Entries appear here, one at a time, on the shared screen.',
    timer: 'Guess timer',
    seconds: 's',
    hostOnly: 'Host-only mode',
    hostOnlyHint: 'Nobody joins; you read entries out and tick who got it. Works on any network.',
    open: 'Open lobby',
    save: 'Save changes',
    loadFile: 'Load a saved game',
    loadError: 'That file isn’t a saved Tell game.',
    meter: {
      ready: 'ready',
      of: 'of',
      needed: 'more needed',
      allSet: 'Ready to go',
      live: 'Players add theirs in the lobby',
    },
  },

  editor: {
    name: 'Name',
    add: 'Add',
    addKey: 'Enter',
    remove: 'Remove',
    row: 'Person',
    paste: 'Paste a list',
    pasteTitle: 'Paste a list',
    pasteHelp:
      'Paste straight from Slack, a doc or a spreadsheet. One person per line as “Name | entry”, “Name: entry” or “Name - entry”, spreadsheet columns, or a name on its own line with their entry underneath.',
    pasteLabel: 'Pasted text',
    preview: 'Preview',
    addRows: 'Add these',
    replaceRows: 'Replace all',
    cancel: 'Cancel',
    close: 'Close',
    sample: 'Sample entries',
    clear: 'Clear all',
    clearConfirm: 'Remove everyone?',
    people: ['person', 'people'] as const,
    needsFix: ['needs a fix', 'need a fix'] as const,
    jump: 'Show me',
    counter: 'characters',
    issues: {
      missingName: 'Add a name',
      missingText: 'Add their entry',
      tooLong: 'Too long',
      duplicateName: 'Same name as another person',
    },
  },

  /** Easter eggs. All short; none can hint at whose entry is whose. */
  eggs: {
    mindMeld: 'Collective consciousness achieved.',
    disguise: 'Master of disguise. Nobody saw that coming.',
    herdBefore: 'Sorry, ',
    herdAfter: '. Apparently it sounded like you.',
    lightning: 'Lightning fast',
    enigma: 'The Enigma',
    enigmaFooled: 'fooled',
    enigmaPeople: ['person', 'people'] as const,
    highlight: {
      enigma: 'You’re the Enigma. You fooled',
      fooled: 'You fooled',
      spotted: 'You spotted',
      none: 'You played it close to the chest.',
    },
    luckyCode: 'Lucky code',
    charged: 'Fully charged.',
    found: 'You found a secret.',
    retroOn: 'Retro mode on',
    retroOff: 'Retro mode off',
    shortcutsTitle: 'Keyboard shortcuts',
    shortcuts: [
      ['Space', 'Next step'],
      ['L', 'Lock guesses'],
      ['R', 'Reveal'],
      ['M', 'Sound on or off'],
      ['F', 'Full screen'],
      ['?', 'This list'],
    ] as const,
    shortcutsMore: '…and a few you’ll have to find.',
    legendsKey: 'dom lab',
  },

  notFound: {
    title: 'Page not found',
    kicker: '404',
    question: 'Whose page is it?',
    answer: 'Nobody’s. It was never here.',
    flip: 'Reveal',
    back: 'Guess again',
  },

  roomCode: 'Room code',
  /** Example code shown in empty code fields. */
  codePlaceholder: 'K7QF',
  more: 'more',

  lobby: {
    joinAt: 'Join at',
    scan: 'or scan',
    joined: 'joined',
    people: ['person', 'people'] as const,
    notJoined: 'not joined yet',
    submitted: 'entry in',
    noEntry: 'no entry yet',
    entries: ['entry', 'entries'] as const,
    waitingFor: 'Waiting for players…',
    needMore: 'Need at least 3 entries to start.',
    edit: 'Back to setup',
    remove: 'Remove',
    opening: 'Opening the room…',
    networkError: 'Couldn’t open the room. Check the connection, or switch to host-only mode.',
    takenError: 'That room code is in use somewhere else.',
    retry: 'Try again',
    newCode: 'Get a new code',
    useHostOnly: 'Switch to host-only',
    hostOnlyTitle: 'Host-only game',
    hostOnlyHint: 'Nobody needs to join. Read each entry out, let people shout, then tick who got it.',
  },

  game: {
    shout: 'Shout your guesses!',
    whoGotIt: 'Who got it? Tick everyone who guessed right.',
    endGame: 'End game',
    endConfirm: 'End this game for everyone?',
    exportBackup: 'Download a backup',
    restartRound: 'Back to lobby',
    newGame: 'New game',
    linkLost: 'Room offline. Reconnecting…',
  },

  play: {
    enterCode: 'Enter the room code',
    codeHint: '4 letters and numbers, on the shared screen',
    go: 'Join',
    hostInstead: 'Hosting? Start a game',
    connecting: 'Connecting to the room…',
    notFound: 'No game with that code yet. Check the shared screen, or wait for the host to open the lobby.',
    reconnecting: 'Reconnecting…',
    changeCode: 'Use a different code',
    whoAreYou: 'Who are you?',
    claimHint: 'Tap your name if the host already added you.',
    orNew: 'Not listed? Type your name',
    yourName: 'Your name',
    joinBtn: 'Join',
    errors: {
      nameRequired: 'Type your name to join.',
      nameTaken: 'Someone already joined with that name. Add an initial?',
      notYou: 'That seat belongs to another device. Join with your own name.',
    },
    youreIn: 'You’re in.',
    lobbyWait: 'Watch the shared screen. The host starts the game.',
    yourEntry: 'Your entry',
    submit: 'Send my entry',
    update: 'Update my entry',
    sent: 'Got it. You can change it until the game starts.',
    here: 'Here so far',
    opensSoon: 'Guessing opens in a moment.',
    lockGuess: 'Lock in guess',
    changeGuess: 'Change my guess',
    yourGuess: 'Your guess',
    gotIt: 'You got it!',
    missed: 'Not this time.',
    noGuess: 'No guess this round.',
    itWas: 'It was',
    youFooled: 'You fooled',
    locked: 'Guesses are locked.',
    secondsLeft: 'seconds left',
  },

  demo: {
    title: 'How a game runs',
    intro: 'A real game in this browser: the shared screen and one player’s screen, side by side. The other players are bots.',
    host: 'Shared screen · the host’s screen on the call',
    phone: 'A player’s screen',
    restart: 'Restart demo',
    steps: [
      { who: 'Host', what: 'Add entries, open the lobby' },
      { who: 'Players', what: 'Join on their own devices with the room code' },
      { who: 'Host', what: 'Start. Each entry is dealt to the shared screen' },
      { who: 'Players', what: 'Read it on their screen and guess whose it is' },
      { who: 'Everyone', what: 'Drumroll, reveal, then the podium' },
    ],
    hint: 'On the player’s screen, type a name and tap Join. Then press Start game on the shared screen (or Space).',
  },
} as const;
