/**
 * Tiny DTCG token build: tokens/tokens.json -> src/tokens/tokens.css + src/tokens/tokens.ts
 *
 * - Group-level `$type` is inherited by children.
 * - `{a.b.c}` aliases are emitted as `var(--a-b-c)` in CSS (so the cascade keeps
 *   the link) and fully resolved in TS (so Three.js materials get real values).
 * - Runs from the Vite plugin in scripts/vite-plugins.ts on every start and on
 *   every save of tokens.json, so one token edit live-reloads UI and 3D scenes.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

type Json = string | number | boolean | null | Json[] | { [key: string]: Json };
type JsonObject = { [key: string]: Json };

interface Token {
  path: string[];
  type: string;
  value: Json;
}

const isObject = (v: Json | undefined): v is JsonObject => typeof v === 'object' && v !== null && !Array.isArray(v);

const ALIAS = /^\{([^}]+)\}$/;

function collect(node: JsonObject, path: string[], inheritedType: string | undefined, out: Token[]): void {
  const type = typeof node.$type === 'string' ? node.$type : inheritedType;
  if ('$value' in node) {
    if (!type) throw new Error(`Token ${path.join('.')} has no $type`);
    out.push({ path, type, value: node.$value as Json });
    return;
  }
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$') || !isObject(child)) continue;
    collect(child, [...path, key], type, out);
  }
}

const cssName = (path: string[]) => `--${path.join('-')}`;

const camel = (s: string) => s.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

function aliasTarget(value: Json): string[] | null {
  if (typeof value !== 'string') return null;
  const m = ALIAS.exec(value);
  return m?.[1] ? m[1].split('.') : null;
}

function cssValue(t: Token): string {
  const target = aliasTarget(t.value);
  if (target) return `var(${cssName(target)})`;
  const v = t.value;
  switch (t.type) {
    case 'dimension':
    case 'duration':
      if (isObject(v)) return `${String(v.value)}${String(v.unit)}`;
      break;
    case 'fontFamily':
      if (Array.isArray(v)) return v.map((f) => (/\s/.test(String(f)) ? `"${String(f)}"` : String(f))).join(', ');
      break;
    case 'cubicBezier':
      if (Array.isArray(v)) return `cubic-bezier(${v.join(', ')})`;
      break;
  }
  return String(v);
}

/** TS values: px dimensions and ms durations become plain numbers. */
function tsValue(t: Token, byPath: Map<string, Token>): Json {
  const target = aliasTarget(t.value);
  if (target) {
    const ref = byPath.get(target.join('.'));
    if (!ref) throw new Error(`Unresolved alias ${String(t.value)} in ${t.path.join('.')}`);
    return tsValue(ref, byPath);
  }
  const v = t.value;
  if ((t.type === 'dimension' || t.type === 'duration') && isObject(v)) {
    return v.unit === 'px' || v.unit === 'ms' ? (v.value as number) : `${String(v.value)}${String(v.unit)}`;
  }
  if (t.type === 'fontFamily') return cssValue(t);
  return v;
}

function setDeep(obj: JsonObject, path: string[], value: Json): void {
  let node = obj;
  path.slice(0, -1).forEach((key) => {
    const k = camel(key);
    if (!isObject(node[k])) node[k] = {};
    node = node[k] as JsonObject;
  });
  node[camel(path[path.length - 1] ?? '')] = value;
}

const HEADER = '/* GENERATED by scripts/build-tokens.ts from tokens/tokens.json. Do not edit. */\n';

/** Builds the token files and returns the resolved token tree (as in tokens.ts). */
export function buildTokens(root: string): JsonObject {
  const source = JSON.parse(readFileSync(resolve(root, 'tokens/tokens.json'), 'utf8')) as JsonObject;
  const tokens: Token[] = [];
  collect(source, [], undefined, tokens);
  const byPath = new Map(tokens.map((t) => [t.path.join('.'), t]));

  const css = `${HEADER}:root {\n${tokens.map((t) => `  ${cssName(t.path)}: ${cssValue(t)};`).join('\n')}\n}\n`;

  const tree: JsonObject = {};
  tokens.forEach((t) => setDeep(tree, t.path, tsValue(t, byPath)));
  const ts = `${HEADER}export const tokens = ${JSON.stringify(tree, null, 2)} as const;\n\nexport type Tokens = typeof tokens;\n`;

  const outDir = resolve(root, 'src/tokens');
  mkdirSync(outDir, { recursive: true });
  writeIfChanged(resolve(outDir, 'tokens.css'), css);
  writeIfChanged(resolve(outDir, 'tokens.ts'), ts);
  return tree;
}

function writeIfChanged(file: string, content: string): void {
  let current = '';
  try {
    current = readFileSync(file, 'utf8');
  } catch {
    /* first build */
  }
  if (current !== content) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content);
  }
}
