/* GENERATED by scripts/build-tokens.ts from tokens/tokens.json. Do not edit. */
export const tokens = {
  "color": {
    "fueled": {
      "perfectBlack": "#000000",
      "perfectWhite": "#F5F5F1",
      "nebula": "#6652FF",
      "techGrey": "#EAEAEA",
      "cryo": "#00A6FF",
      "solar": "#FF52B7",
      "nova": "#FBBC09",
      "lilac": "#B9AEFF",
      "deepViolet": "#4A3BD6"
    },
    "neutral": {
      "300": "#B4B4BC",
      "500": "#55555F",
      "700": "#26262E",
      "800": "#17171C",
      "900": "#0D0D10"
    },
    "bg": "#000000",
    "surface": "rgba(255, 255, 255, 0.05)",
    "surfaceRaised": "rgba(23, 23, 28, 0.62)",
    "surfaceSolid": "#17171C",
    "border": "rgba(255, 255, 255, 0.12)",
    "borderStrong": "rgba(255, 255, 255, 0.24)",
    "text": "#F5F5F1",
    "textMuted": "#B4B4BC",
    "textInverse": "#000000",
    "accent": "#6652FF",
    "highlight": "#00A6FF",
    "player": {
      "1": "#00A6FF",
      "2": "#FF52B7",
      "3": "#FBBC09",
      "4": "#6652FF"
    },
    "glow": {
      "pink": "#FF52B7",
      "violet": "#6652FF",
      "lilac": "#B9AEFF"
    }
  },
  "font": {
    "family": {
      "base": "Aeonik, system-ui, -apple-system, \"Segoe UI\", sans-serif"
    },
    "weight": {
      "base": 500
    },
    "size": {
      "hostHero": 152,
      "hostDisplay": 96,
      "hostTitle": 64,
      "hostBody": 48,
      "hostLabel": 32,
      "phoneDisplay": 40,
      "phoneTitle": 26,
      "phoneBody": 18,
      "phoneLabel": 14,
      "pageDisplay": 72
    },
    "lineHeight": {
      "tight": 1.05,
      "base": 1.25
    },
    "letterSpacing": {
      "tight": "-0.02em",
      "label": "0.06em",
      "code": "0.4em"
    }
  },
  "space": {
    "1": 4,
    "2": 8,
    "3": 12,
    "4": 16,
    "5": 24,
    "6": 32,
    "7": 48,
    "8": 64,
    "9": 96
  },
  "size": {
    "tapTarget": 48,
    "stageWidth": 1920,
    "stageHeight": 1080,
    "itemWidth": 1280,
    "phoneWidth": 420,
    "itemHeight": 620,
    "itemOffsetY": -40,
    "cardWidth": 1320,
    "stagePortraitWidth": 1080,
    "stagePortraitHeight": 1920,
    "cardWidthPortrait": 960,
    "itemHeightPortrait": 960,
    "itemOffsetYPortrait": -200,
    "itemPadding": 80,
    "chip": 72,
    "builtbyHost": 40,
    "builtbyPage": 28,
    "playWide": 880,
    "logoPage": 36,
    "logoCompact": 20,
    "logoHost": 29,
    "builtbyCompact": 20
  },
  "radius": {
    "pill": 999,
    "card": 32,
    "panel": 24,
    "field": 18,
    "tile": 16
  },
  "blur": {
    "glass": 24,
    "glow": 80
  },
  "gradient": {
    "glow": "linear-gradient(135deg, var(--color-fueled-solar), var(--color-fueled-nebula) 60%, var(--color-fueled-deep-violet))",
    "text": "linear-gradient(90deg, var(--color-fueled-lilac), var(--color-fueled-solar))"
  },
  "borderWidth": {
    "base": 2,
    "strong": 4,
    "hairline": 1
  },
  "duration": {
    "fast": 150,
    "base": 300,
    "slow": 600,
    "entrance": 1400,
    "reveal": 1800,
    "bootMin": 1400,
    "stagger": 220,
    "drift": 22000
  },
  "easing": {
    "standard": [
      0.2,
      0,
      0,
      1
    ],
    "emphasized": [
      0.3,
      0,
      0,
      1.3
    ]
  },
  "opacity": {
    "dim": 0.35,
    "muted": 0.6,
    "glow": 0.85,
    "glowCalm": 0.32
  },
  "scene": {
    "lightIntensity": 1.4,
    "ambientIntensity": 0.35
  }
} as const;

export type Tokens = typeof tokens;
